import {
  Char,
  type EncodingImpl,
  EncodingRegistration,
} from "../common-internal.ts";

const ASCII_8BIT_IMPL: EncodingImpl = {
  asciiCompatible: true,

  *chars(bytes: Uint8Array): IterableIterator<Char> {
    for (let i = 0; i < bytes.length; i++) {
      const unicode = bytes[i] < 0x80 ? bytes[i] : undefined;
      yield Char(i, i + 1, true, unicode);
    }
  },
};

export default [
  EncodingRegistration(ASCII_8BIT_IMPL, "ASCII-8BIT", ["BINARY"]),
  EncodingRegistration(ASCII_8BIT_IMPL, "ISO-8859-1", ["ISO8859-1"]),
  EncodingRegistration(ASCII_8BIT_IMPL, "ISO-8859-2", ["ISO8859-2"]),
  EncodingRegistration(ASCII_8BIT_IMPL, "ISO-8859-3", ["ISO8859-3"]),
  EncodingRegistration(ASCII_8BIT_IMPL, "ISO-8859-4", ["ISO8859-4"]),
  EncodingRegistration(ASCII_8BIT_IMPL, "ISO-8859-5", ["ISO8859-5"]),
  EncodingRegistration(ASCII_8BIT_IMPL, "ISO-8859-6", ["ISO8859-6"]),
  EncodingRegistration(ASCII_8BIT_IMPL, "ISO-8859-7", ["ISO8859-7"]),
  EncodingRegistration(ASCII_8BIT_IMPL, "ISO-8859-8", ["ISO8859-8"]),
  EncodingRegistration(ASCII_8BIT_IMPL, "ISO-8859-9", ["ISO8859-9"]),
  EncodingRegistration(ASCII_8BIT_IMPL, "ISO-8859-10", ["ISO8859-10"]),
  EncodingRegistration(ASCII_8BIT_IMPL, "ISO-8859-11", ["ISO8859-11"]),
  EncodingRegistration(ASCII_8BIT_IMPL, "ISO-8859-13", ["ISO8859-13"]),
  EncodingRegistration(ASCII_8BIT_IMPL, "ISO-8859-14", ["ISO8859-14"]),
  EncodingRegistration(ASCII_8BIT_IMPL, "ISO-8859-15", ["ISO8859-15"]),
  EncodingRegistration(ASCII_8BIT_IMPL, "ISO-8859-16", ["ISO8859-16"]),
  EncodingRegistration(ASCII_8BIT_IMPL, "KOI8-R", ["CP878"]),
  EncodingRegistration(ASCII_8BIT_IMPL, "KOI8-U", []),
  EncodingRegistration(ASCII_8BIT_IMPL, "Windows-874", ["CP874"]),
  EncodingRegistration(ASCII_8BIT_IMPL, "Windows-1250", ["CP1250"]),
  EncodingRegistration(ASCII_8BIT_IMPL, "Windows-1251", ["CP1251"]),
  EncodingRegistration(ASCII_8BIT_IMPL, "Windows-1252", ["CP1252"]),
  EncodingRegistration(ASCII_8BIT_IMPL, "Windows-1253", ["CP1253"]),
  EncodingRegistration(ASCII_8BIT_IMPL, "Windows-1254", ["CP1254"]),
  EncodingRegistration(ASCII_8BIT_IMPL, "Windows-1255", ["CP1255"]),
  EncodingRegistration(ASCII_8BIT_IMPL, "Windows-1256", ["CP1256"]),
  EncodingRegistration(ASCII_8BIT_IMPL, "Windows-1257", ["CP1257"]),
  EncodingRegistration(ASCII_8BIT_IMPL, "Windows-1258", ["CP1258"]),
  EncodingRegistration(ASCII_8BIT_IMPL, "IBM437", ["CP437"]),
  EncodingRegistration(ASCII_8BIT_IMPL, "IBM720", ["CP720"]),
  EncodingRegistration(ASCII_8BIT_IMPL, "IBM737", ["CP737"]),
  EncodingRegistration(ASCII_8BIT_IMPL, "IBM775", ["CP775"]),
  EncodingRegistration(ASCII_8BIT_IMPL, "IBM850", ["CP850"]),
  EncodingRegistration(ASCII_8BIT_IMPL, "IBM852", []),
  EncodingRegistration(ASCII_8BIT_IMPL, "CP852", []),
  EncodingRegistration(ASCII_8BIT_IMPL, "IBM855", []),
  EncodingRegistration(ASCII_8BIT_IMPL, "CP855", []),
  EncodingRegistration(ASCII_8BIT_IMPL, "IBM857", ["CP857"]),
  EncodingRegistration(ASCII_8BIT_IMPL, "IBM860", ["CP860"]),
  EncodingRegistration(ASCII_8BIT_IMPL, "IBM861", ["CP861"]),
  EncodingRegistration(ASCII_8BIT_IMPL, "IBM862", ["CP862"]),
  EncodingRegistration(ASCII_8BIT_IMPL, "IBM863", ["CP863"]),
  EncodingRegistration(ASCII_8BIT_IMPL, "IBM864", ["CP864"]),
  EncodingRegistration(ASCII_8BIT_IMPL, "IBM865", ["CP865"]),
  EncodingRegistration(ASCII_8BIT_IMPL, "IBM866", ["CP866"]),
  EncodingRegistration(ASCII_8BIT_IMPL, "IBM869", ["CP869"]),
  EncodingRegistration(ASCII_8BIT_IMPL, "GB1988", []),
  EncodingRegistration(ASCII_8BIT_IMPL, "macCentEuro", []),
  EncodingRegistration(ASCII_8BIT_IMPL, "macCroatian", []),
  EncodingRegistration(ASCII_8BIT_IMPL, "macCyrillic", []),
  EncodingRegistration(ASCII_8BIT_IMPL, "macGreek", []),
  EncodingRegistration(ASCII_8BIT_IMPL, "macIceland", []),
  EncodingRegistration(ASCII_8BIT_IMPL, "macRoman", []),
  EncodingRegistration(ASCII_8BIT_IMPL, "macRomania", []),
  EncodingRegistration(ASCII_8BIT_IMPL, "macThai", []),
  EncodingRegistration(ASCII_8BIT_IMPL, "macTurkish", []),
  EncodingRegistration(ASCII_8BIT_IMPL, "macUkraine", []),
  EncodingRegistration(ASCII_8BIT_IMPL, "TIS-620", []),
] satisfies EncodingRegistration[];
